name: amplify_storage_s3
description: The Amplify Flutter Storage category plugin using the AWS S3 provider.
version: 1.0.0-next.0+3
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/storage/amplify_storage_s3
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

# Helps `pana` since we do not use Flutter plugins for most platforms
platforms:
  ios:
  android:
  macos:
  windows:
  linux:
  web:

dependencies:
  amplify_core: ">=1.0.0-next.0+2 <1.0.0-next.1"
  amplify_storage_s3_dart: ^0.1.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  amplify_lints: ^2.0.0
  amplify_test:
    path: ../../amplify_test
  flutter_test:
    sdk: flutter
